#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x8FE99503132D7742 (antonio@gnu.org)
#
Name     : plzip
Version  : 1.8
Release  : 2
URL      : http://download.savannah.gnu.org/releases/lzip/plzip/plzip-1.8.tar.gz
Source0  : http://download.savannah.gnu.org/releases/lzip/plzip/plzip-1.8.tar.gz
Source99 : http://download.savannah.gnu.org/releases/lzip/plzip/plzip-1.8.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: plzip-bin = %{version}-%{release}
Requires: plzip-license = %{version}-%{release}
Requires: plzip-man = %{version}-%{release}
BuildRequires : lzlib-dev

%description
Description
Plzip is a massively parallel (multi-threaded) implementation of lzip, fully
compatible with lzip 1.4 or newer. Plzip uses the lzlib compression library.

%package bin
Summary: bin components for the plzip package.
Group: Binaries
Requires: plzip-license = %{version}-%{release}
Requires: plzip-man = %{version}-%{release}

%description bin
bin components for the plzip package.


%package doc
Summary: doc components for the plzip package.
Group: Documentation
Requires: plzip-man = %{version}-%{release}

%description doc
doc components for the plzip package.


%package license
Summary: license components for the plzip package.
Group: Default

%description license
license components for the plzip package.


%package man
Summary: man components for the plzip package.
Group: Default

%description man
man components for the plzip package.


%prep
%setup -q -n plzip-1.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547166752
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1547166752
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/plzip
cp COPYING %{buildroot}/usr/share/package-licenses/plzip/COPYING
%make_install
## install_append content
ln -s plzip %{buildroot}/usr/bin/lzip
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lzip
/usr/bin/plzip

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/info/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/plzip/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/plzip.1
